import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Search,Library,Heart,Play,Pause,SkipBack,SkipForward,Shuffle,Repeat,Volume2,Maximize2,Minimize2,MoreHorizontal,Plus,Music2,X,ChevronDown,Clock3, ListMusic} from 'lucide-react';
import './styles.css';

const songs=[
 {id:1,title:'Midnight Drive',artist:'Neon Avenue',album:'After Dark',genre:'Electronic',duration:214,art:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80'},
 {id:2,title:'Ocean Eyes',artist:'Luna Vale',album:'Blue Hour',genre:'Indie',duration:238,art:'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=900&q=80'},
 {id:3,title:'Afterglow',artist:'Static Bloom',album:'Afterglow',genre:'Alternative',duration:196,art:'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80'},
 {id:4,title:'Gravity',artist:'Kairo',album:'Gravity',genre:'Pop',duration:202,art:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=80'},
 {id:5,title:'Parallel Lines',artist:'Velvet Static',album:'Parallel',genre:'Electronic',duration:257,art:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=80'},
 {id:6,title:'Golden Skies',artist:'Mira North',album:'Sunset Radio',genre:'Chill',duration:221,art:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80'},
 {id:7,title:'Runaway',artist:'The Satellites',album:'Open Roads',genre:'Rock',duration:231,art:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=80'},
 {id:8,title:'Velvet Rain',artist:'Noir Bloom',album:'Night Letters',genre:'R&B',duration:247,art:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80'}
];
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function App(){
 const [page,setPage]=useState('home'),[current,setCurrent]=useState(songs[0]),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[volume,setVolume]=useState(.8),[liked,setLiked]=useState(new Set([2,6])),[queue,setQueue]=useState(songs),[expanded,setExpanded]=useState(false),[query,setQuery]=useState('');
 const audio=useRef(null);
 useEffect(()=>{if(!audio.current)return; audio.current.volume=volume;},[volume]);
 useEffect(()=>{const a=audio.current;if(!a)return; const tick=()=>setProgress(a.currentTime||0);const ended=()=>next();a.addEventListener('timeupdate',tick);a.addEventListener('ended',ended);return()=>{a.removeEventListener('timeupdate',tick);a.removeEventListener('ended',ended)}},[current,queue]);
 useEffect(()=>{const a=audio.current;if(!a)return; a.src=current.url||''; if(current.url){a.load(); if(playing)a.play().catch(()=>setPlaying(false));}},[current]);
 const filtered=useMemo(()=>songs.filter(s=>(s.title+' '+s.artist+' '+s.album).toLowerCase().includes(query.toLowerCase())),[query]);
 const toggleLike=id=>setLiked(x=>{const n=new Set(x);n.has(id)?n.delete(id):n.add(id);return n});
 const play=s=>{setCurrent(s);setPlaying(true)};
 const next=()=>{const i=queue.findIndex(s=>s.id===current.id);play(queue[(i+1)%queue.length])};
 const prev=()=>{const i=queue.findIndex(s=>s.id===current.id);play(queue[(i-1+queue.length)%queue.length])};
 const nav=p=>{setPage(p);setExpanded(false)};
 const hero=page==='home';
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="logo"><Music2 size={21}/></div><span>MyMusic</span></div><nav><button className={page==='home'?'active':''} onClick={()=>nav('home')}><Home/>Home</button><button className={page==='search'?'active':''} onClick={()=>nav('search')}><Search/>Search</button><button className={page==='library'?'active':''} onClick={()=>nav('library')}><Library/>Your Library</button></nav><div className="sideLabel">YOUR MUSIC</div><button onClick={()=>nav('liked')}><Heart/>Liked Songs</button><button onClick={()=>nav('playlists')}><ListMusic/>Playlists</button><div className="drive"><div className="driveDot"></div><div><b>Google Drive</b><span>Music source</span></div></div></aside>
  <main className="main"><header><div className="mobileBrand"><div className="logo"><Music2 size={19}/></div>MyMusic</div>{page==='search'?<div className="searchbar"><Search/><input autoFocus placeholder="What do you want to play?" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<X onClick={()=>setQuery('')}/>}</div>:<div className="topSearch" onClick={()=>nav('search')}><Search size={19}/><span>Search your library</span></div>}<div className="profile">A</div></header>
   {hero&&<section className="hero"><div className="heroArt" style={{backgroundImage:`url(${songs[0].art})`}}></div><div className="heroText"><span>FEATURED RELEASE</span><h1>After Dark</h1><p>A late-night collection for long drives, quiet rooms and everything in between.</p><div className="heroBtns"><button className="primary" onClick={()=>play(songs[0])}><Play fill="currentColor"/> Play</button><button className="circle" onClick={()=>toggleLike(songs[0].id)}><Heart fill={liked.has(songs[0].id)?'currentColor':'none'}/></button></div></div></section>}
   {page==='home'&&<><Section title="Recently played" songs={songs.slice(0,5)} play={play} liked={liked} toggleLike={toggleLike}/><Section title="Made for you" songs={songs.slice(3,8)} play={play} liked={liked} toggleLike={toggleLike}/></>}
   {page==='search'&&<><h2 className="pageTitle">Search results</h2>{query?<Section title={`${filtered.length} results`} songs={filtered} play={play} liked={liked} toggleLike={toggleLike} list/>:<div className="browse"><h3>Browse all</h3><div className="genres">{['Made for you','Electronic','Indie','Chill','Pop','R&B','Rock','Focus'].map((g,i)=><div key={g} className={`genre g${i}`} onClick={()=>setQuery(g)}>{g}</div>)}</div></div>}</>}
   {page==='library'&&<><h2 className="pageTitle">Your Library</h2><div className="tabs"><span className="selected">All</span><span>Albums</span><span>Artists</span><span>Playlists</span></div><Section title="Your songs" songs={songs} play={play} liked={liked} toggleLike={toggleLike} list/></>}
   {page==='liked'&&<><div className="likedHead"><div className="likedArt"><Heart fill="currentColor"/></div><div><span>PLAYLIST</span><h1>Liked Songs</h1><p>{liked.size} songs you love</p></div></div><Section title="" songs={songs.filter(s=>liked.has(s.id))} play={play} liked={liked} toggleLike={toggleLike} list/></>}
   {page==='playlists'&&<><h2 className="pageTitle">Playlists</h2><div className="playlistGrid"><div className="create" onClick={()=>alert('Playlist creation can be connected to your database next.')}><Plus/><b>Create playlist</b><span>Build your own collection</span></div>{['Late Night','Favorites','Study Mode'].map((p,i)=><div className="playlist" key={p}><img src={songs[i+2].art}/><b>{p}</b><span>{i+3} songs</span></div>)}</div></>}
  </main>
  <audio ref={audio}/>
  <div className="player"><div className="trackInfo"><img src={current.art}/><div><b>{current.title}</b><span>{current.artist}</span></div><Heart size={18} className="likeBtn" fill={liked.has(current.id)?'currentColor':'none'} onClick={()=>toggleLike(current.id)}/></div><div className="controls"><div className="controlBtns"><button><Shuffle size={17}/></button><button onClick={prev}><SkipBack size={20} fill="currentColor"/></button><button className="playBtn" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={20} fill="currentColor"/>:<Play size={20} fill="currentColor"/>}</button><button onClick={next}><SkipForward size={20} fill="currentColor"/></button><button><Repeat size={17}/></button></div><div className="progress"><span>{fmt(progress)}</span><input type="range" min="0" max={current.duration} value={progress} onChange={e=>{setProgress(+e.target.value);if(audio.current)audio.current.currentTime=+e.target.value}}/><span>{fmt(current.duration)}</span></div></div><div className="playerRight"><Volume2 size={18}/><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(+e.target.value)}/><button onClick={()=>setExpanded(true)}><Maximize2 size={18}/></button></div></div>
  {expanded&&<div className="nowPlaying"><button className="close" onClick={()=>setExpanded(false)}><ChevronDown/></button><div className="npGlow" style={{backgroundImage:`url(${current.art})`}}></div><img className="npArt" src={current.art}/><div className="npMeta"><div><h1>{current.title}</h1><p>{current.artist} · {current.album}</p></div><Heart fill={liked.has(current.id)?'currentColor':'none'} onClick={()=>toggleLike(current.id)}/></div><div className="npProgress"><input type="range" min="0" max={current.duration} value={progress} onChange={e=>{setProgress(+e.target.value);if(audio.current)audio.current.currentTime=+e.target.value}}/><div><span>{fmt(progress)}</span><span>{fmt(current.duration)}</span></div></div><div className="npControls"><Shuffle/><SkipBack fill="currentColor" onClick={prev}/><button onClick={()=>setPlaying(!playing)}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><SkipForward fill="currentColor" onClick={next}/><Repeat/></div></div>}
 </div>
}
function Section({title,songs,play,liked,toggleLike,list}){return <section className={list?'section listSection':'section'}>{title&&<div className="sectionHead"><h2>{title}</h2><span>Show all</span></div>}{list?<div className="songList">{songs.map((s,i)=><div className="row" key={s.id} onDoubleClick={()=>play(s)}><span className="num">{i+1}</span><img src={s.art}/><div className="rowMain"><b>{s.title}</b><span>{s.artist}</span></div><span className="album">{s.album}</span><button onClick={()=>toggleLike(s.id)}><Heart size={17} fill={liked.has(s.id)?'currentColor':'none'}/></button><span className="duration">{fmt(s.duration)}</span><button><MoreHorizontal size={18}/></button></div>)}</div>:<div className="cards">{songs.map(s=><div className="card" key={s.id} onDoubleClick={()=>play(s)}><div className="coverWrap"><img src={s.art}/><button className="cardPlay" onClick={()=>play(s)}><Play size={18} fill="currentColor"/></button></div><div className="cardTitle">{s.title}</div><div className="cardSub">{s.artist}</div></div>)}</div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
